# This is a basic workflow to help you get started with Actions

name: Black Duck

on:
  workflow_dispatch:

jobs:
  detect:
    name: Scan with Black Duck
    runs-on: macos-latest

    steps:  
      - uses: actions/checkout@v2
      - name: Run Detect7
        run: bash <(curl -s -L https://detect.synopsys.com/detect7.sh) 
